version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"   # MQTT
      - "9001:9001"   # WebSocket
    volumes:
      - ./mosquitto/config:/mosquitto/config

volumes:
  mosquitto-data:
    driver: local
  mosquitto-log:
    driver: local
